{
	"title": "Fallbacks | ü¶úÔ∏èüîó Langchain",
	"url": "https://python.langchain.com/docs/guides/fallbacks",
	"html": "Fallbacks\nFallbacks\n\nWhen working with language models, you may often encounter issues from the underlying APIs, whether these be rate limiting or downtime. Therefore, as you go to move your LLM applications into production it becomes more and more important to safeguard against these. That's why we've introduced the concept of fallbacks.\n\nA fallback is an alternative plan that may be used in an emergency.\n\nCrucially, fallbacks can be applied not only on the LLM level but on the whole runnable level. This is important because often times different models require different prompts. So if your call to OpenAI fails, you don't just want to send the same prompt to Anthropic - you probably want to use a different prompt template and send a different version there.\n\nFallback for LLM API Errors‚Äã\n\nThis is maybe the most common use case for fallbacks. A request to an LLM API can fail for a variety of reasons - the API could be down, you could have hit rate limits, any number of things. Therefore, using fallbacks can help protect against these types of things.\n\nIMPORTANT: By default, a lot of the LLM wrappers catch errors and retry. You will most likely want to turn those off when working with fallbacks. Otherwise the first wrapper will keep on retrying and not failing.\n\nfrom langchain.chat_models import ChatAnthropic, ChatOpenAI\n\n\nFirst, let's mock out what happens if we hit a RateLimitError from OpenAI\n\nfrom unittest.mock import patch\n\nfrom openai.error import RateLimitError\n\n# Note that we set max_retries = 0 to avoid retrying on RateLimits, etc\nopenai_llm = ChatOpenAI(max_retries=0)\nanthropic_llm = ChatAnthropic()\nllm = openai_llm.with_fallbacks([anthropic_llm])\n\n# Let's use just the OpenAI LLm first, to show that we run into an error\nwith patch(\"openai.ChatCompletion.create\", side_effect=RateLimitError()):\n    try:\n        print(openai_llm.invoke(\"Why did the chicken cross the road?\"))\n    except:\n        print(\"Hit error\")\n\n    Hit error\n\n# Now let's try with fallbacks to Anthropic\nwith patch(\"openai.ChatCompletion.create\", side_effect=RateLimitError()):\n    try:\n        print(llm.invoke(\"Why did the chicken cross the road?\"))\n    except:\n        print(\"Hit error\")\n\n    content=' I don\\'t actually know why the chicken crossed the road, but here are some possible humorous answers:\\n\\n- To get to the other side!\\n\\n- It was too chicken to just stand there. \\n\\n- It wanted a change of scenery.\\n\\n- It wanted to show the possum it could be done.\\n\\n- It was on its way to a poultry farmers\\' convention.\\n\\nThe joke plays on the double meaning of \"the other side\" - literally crossing the road to the other side, or the \"other side\" meaning the afterlife. So it\\'s an anti-joke, with a silly or unexpected pun as the answer.' additional_kwargs={} example=False\n\n\nWe can use our \"LLM with Fallbacks\" as we would a normal LLM.\n\nfrom langchain.prompts import ChatPromptTemplate\n\nprompt = ChatPromptTemplate.from_messages(\n    [\n        (\n            \"system\",\n            \"You're a nice assistant who always includes a compliment in your response\",\n        ),\n        (\"human\", \"Why did the {animal} cross the road\"),\n    ]\n)\nchain = prompt | llm\nwith patch(\"openai.ChatCompletion.create\", side_effect=RateLimitError()):\n    try:\n        print(chain.invoke({\"animal\": \"kangaroo\"}))\n    except:\n        print(\"Hit error\")\n\n    content=\" I don't actually know why the kangaroo crossed the road, but I can take a guess! Here are some possible reasons:\\n\\n- To get to the other side (the classic joke answer!)\\n\\n- It was trying to find some food or water \\n\\n- It was trying to find a mate during mating season\\n\\n- It was fleeing from a predator or perceived threat\\n\\n- It was disoriented and crossed accidentally \\n\\n- It was following a herd of other kangaroos who were crossing\\n\\n- It wanted a change of scenery or environment \\n\\n- It was trying to reach a new habitat or territory\\n\\nThe real reason is unknown without more context, but hopefully one of those potential explanations does the joke justice! Let me know if you have any other animal jokes I can try to decipher.\" additional_kwargs={} example=False\n\nFallback for Sequences‚Äã\n\nWe can also create fallbacks for sequences, that are sequences themselves. Here we do that with two different models: ChatOpenAI and then normal OpenAI (which does not use a chat model). Because OpenAI is NOT a chat model, you likely want a different prompt.\n\n# First let's create a chain with a ChatModel\n# We add in a string output parser here so the outputs between the two are the same type\nfrom langchain.schema.output_parser import StrOutputParser\n\nchat_prompt = ChatPromptTemplate.from_messages(\n    [\n        (\n            \"system\",\n            \"You're a nice assistant who always includes a compliment in your response\",\n        ),\n        (\"human\", \"Why did the {animal} cross the road\"),\n    ]\n)\n# Here we're going to use a bad model name to easily create a chain that will error\nchat_model = ChatOpenAI(model_name=\"gpt-fake\")\nbad_chain = chat_prompt | chat_model | StrOutputParser()\n\n# Now lets create a chain with the normal OpenAI model\nfrom langchain.llms import OpenAI\nfrom langchain.prompts import PromptTemplate\n\nprompt_template = \"\"\"Instructions: You should always include a compliment in your response.\n\nQuestion: Why did the {animal} cross the road?\"\"\"\nprompt = PromptTemplate.from_template(prompt_template)\nllm = OpenAI()\ngood_chain = prompt | llm\n\n# We can now create a final chain which combines the two\nchain = bad_chain.with_fallbacks([good_chain])\nchain.invoke({\"animal\": \"turtle\"})\n\n    '\\n\\nAnswer: The turtle crossed the road to get to the other side, and I have to say he had some impressive determination.'\n\nFallback for Long Inputs‚Äã\n\nOne of the big limiting factors of LLMs is their context window. Usually, you can count and track the length of prompts before sending them to an LLM, but in situations where that is hard/complicated, you can fallback to a model with a longer context length.\n\nshort_llm = ChatOpenAI()\nlong_llm = ChatOpenAI(model=\"gpt-3.5-turbo-16k\")\nllm = short_llm.with_fallbacks([long_llm])\n\ninputs = \"What is the next number: \" + \", \".join([\"one\", \"two\"] * 3000)\n\ntry:\n    print(short_llm.invoke(inputs))\nexcept Exception as e:\n    print(e)\n\n    This model's maximum context length is 4097 tokens. However, your messages resulted in 12012 tokens. Please reduce the length of the messages.\n\ntry:\n    print(llm.invoke(inputs))\nexcept Exception as e:\n    print(e)\n\n    content='The next number in the sequence is two.' additional_kwargs={} example=False\n\nFallback to Better Model‚Äã\n\nOften times we ask models to output format in a specific format (like JSON). Models like GPT-3.5 can do this okay, but sometimes struggle. This naturally points to fallbacks - we can try with GPT-3.5 (faster, cheaper), but then if parsing fails we can use GPT-4.\n\nfrom langchain.output_parsers import DatetimeOutputParser\n\nprompt = ChatPromptTemplate.from_template(\n    \"what time was {event} (in %Y-%m-%dT%H:%M:%S.%fZ format - only return this value)\"\n)\n\n# In this case we are going to do the fallbacks on the LLM + output parser level\n# Because the error will get raised in the OutputParser\nopenai_35 = ChatOpenAI() | DatetimeOutputParser()\nopenai_4 = ChatOpenAI(model=\"gpt-4\") | DatetimeOutputParser()\n\nonly_35 = prompt | openai_35\nfallback_4 = prompt | openai_35.with_fallbacks([openai_4])\n\ntry:\n    print(only_35.invoke({\"event\": \"the superbowl in 1994\"}))\nexcept Exception as e:\n    print(f\"Error: {e}\")\n\n    Error: Could not parse datetime string: The Super Bowl in 1994 took place on January 30th at 3:30 PM local time. Converting this to the specified format (%Y-%m-%dT%H:%M:%S.%fZ) results in: 1994-01-30T15:30:00.000Z\n\ntry:\n    print(fallback_4.invoke({\"event\": \"the superbowl in 1994\"}))\nexcept Exception as e:\n    print(f\"Error: {e}\")\n\n    1994-01-30 15:30:00\n\nPrevious\nComparing Chain Outputs\nNext\nRun LLMs locally"
}